/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.JOptionPane;

/**
 *
 * @author yoons
 */
public class Principal extends javax.swing.JFrame {

    int Item1,Item2;
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void borrar(){
        txtB1.setText(null);
        jLblB2.setText(null);
        ComboBoxB1.setSelectedIndex(0);
        ComboBoxB2.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnAtras = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jLbltxt1 = new javax.swing.JLabel();
        jLbltxt2 = new javax.swing.JLabel();
        ComboBoxB1 = new javax.swing.JComboBox<>();
        ComboBoxB2 = new javax.swing.JComboBox<>();
        jLbltxt3 = new javax.swing.JLabel();
        jLblB2 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtB1 = new javax.swing.JTextField();
        jLbltxt4 = new javax.swing.JLabel();
        jLbltxt5 = new javax.swing.JLabel();
        jLblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnAtras.setBackground(new java.awt.Color(204, 204, 204));
        BtnAtras.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnAtras.setText("Atrás");
        BtnAtras.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        BtnAtras.setBorderPainted(false);
        BtnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(BtnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        BtnSalir.setBackground(new java.awt.Color(204, 204, 204));
        BtnSalir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        BtnSalir.setBorderPainted(false);
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 60, 30));

        jLbltxt1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLbltxt1.setText("Introducir Numero:");
        getContentPane().add(jLbltxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLbltxt2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLbltxt2.setText("Base a la que desea convertir");
        getContentPane().add(jLbltxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        ComboBoxB1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        ComboBoxB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 Binario", "3", "4", "5", "6", "7", "8 Octal", "9", "10 Decimal", "11", "12", "14", "15", "16 Hexadecimal" }));
        ComboBoxB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxB1ActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        ComboBoxB2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        ComboBoxB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 Binario", "3", "4", "5", "6", "7", "8 Octal", "9", "10 Decimal", "11", "12", "14", "15", "16 Hexadecimal" }));
        ComboBoxB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxB2ActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        jLbltxt3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLbltxt3.setText("Resultado:");
        getContentPane().add(jLbltxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLblB2.setBackground(new java.awt.Color(255, 255, 255));
        jLblB2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLblB2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLblB2.setOpaque(true);
        getContentPane().add(jLblB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 360, 30));

        btnCalcular.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        btnLimpiar.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        txtB1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtB1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 330, 30));

        jLbltxt4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLbltxt4.setText("Base que tiene:");
        getContentPane().add(jLbltxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 30));

        jLbltxt5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLbltxt5.setText("(Maximo 5 numeros)");
        getContentPane().add(jLbltxt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        jLblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Conversor_de_Bases_2.jpg"))); // NOI18N
        getContentPane().add(jLblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAtrasMouseClicked
        Datos datos= new Datos();
        datos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAtrasMouseClicked

    private void ComboBoxB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxB1ActionPerformed

    private void ComboBoxB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxB2ActionPerformed

    private void txtB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtB1ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        borrar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if(txtB1.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Favor de Ingresar un numero");
        }
       BoxB1();
       BoxB1();
       
    }//GEN-LAST:event_btnCalcularActionPerformed
    
    public void BoxB1(){
        Item1= ComboBoxB1.getSelectedIndex();
        Item1=Item1+2;
       JOptionPane.showMessageDialog(null, "El item seleccionado es: "+Item1);
    }
    public void BoxB2(){
        Item2= ComboBoxB2.getSelectedIndex();
        Item2=Item2+2;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JComboBox<String> ComboBoxB1;
    private javax.swing.JComboBox<String> ComboBoxB2;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLblB2;
    private javax.swing.JLabel jLblFondo;
    private javax.swing.JLabel jLbltxt1;
    private javax.swing.JLabel jLbltxt2;
    private javax.swing.JLabel jLbltxt3;
    private javax.swing.JLabel jLbltxt4;
    private javax.swing.JLabel jLbltxt5;
    private javax.swing.JTextField txtB1;
    // End of variables declaration//GEN-END:variables
}
